<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Mediation and Path Analysis – Statistics II</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./efa.html" rel="next">
<link href="./multiplelinear.html" rel="prev">
<link href="./images/cover.avif" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-745db6197ef74dcdda39b41813071fb2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./path.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mediation and Path Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics II</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Basic data structures in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./process.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data processing, transformation and ploting in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Non-parametric statistical tests in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovabetween.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">One-way between-subjects Analysis of Variance (One-way ANOVA) in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anovawithin.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">One-way within-subjects Analysis of Variance (Repeated one-way ANOVA) in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova2factor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Two-way between-subjects Analysis of Variance (Two-way ANOVA) in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simplelinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Simple Linear regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiplelinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Multiple Linear regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./path.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mediation and Path Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./efa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Exploratory Factor Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./presentations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Presentations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#mediation-analysis" id="toc-mediation-analysis" class="nav-link active" data-scroll-target="#mediation-analysis"><span class="header-section-number">9.1</span> Mediation analysis</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"><span class="header-section-number">9.2</span> Example</a></li>
  <li><a href="#import-the-dataset" id="toc-import-the-dataset" class="nav-link" data-scroll-target="#import-the-dataset"><span class="header-section-number">9.3</span> Import the dataset</a>
  <ul class="collapse">
  <li><a href="#baron-kenny-method" id="toc-baron-kenny-method" class="nav-link" data-scroll-target="#baron-kenny-method"><span class="header-section-number">9.3.1</span> Baron &amp; Kenny method</a></li>
  <li><a href="#mediation-analysis-with-r" id="toc-mediation-analysis-with-r" class="nav-link" data-scroll-target="#mediation-analysis-with-r"><span class="header-section-number">9.3.2</span> Mediation Analysis with R</a></li>
  </ul></li>
  <li><a href="#path-analysis" id="toc-path-analysis" class="nav-link" data-scroll-target="#path-analysis"><span class="header-section-number">9.4</span> Path analysis</a>
  <ul class="collapse">
  <li><a href="#basic-concepts" id="toc-basic-concepts" class="nav-link" data-scroll-target="#basic-concepts"><span class="header-section-number">9.4.1</span> Basic concepts</a></li>
  <li><a href="#model-identification" id="toc-model-identification" class="nav-link" data-scroll-target="#model-identification"><span class="header-section-number">9.4.2</span> Model Identification</a></li>
  <li><a href="#model-fit-in-path-analysis" id="toc-model-fit-in-path-analysis" class="nav-link" data-scroll-target="#model-fit-in-path-analysis"><span class="header-section-number">9.4.3</span> Model Fit in path analysis</a></li>
  </ul></li>
  <li><a href="#import-the-dataset-1" id="toc-import-the-dataset-1" class="nav-link" data-scroll-target="#import-the-dataset-1"><span class="header-section-number">9.5</span> Import the dataset</a></li>
  <li><a href="#path-analysis-in-r" id="toc-path-analysis-in-r" class="nav-link" data-scroll-target="#path-analysis-in-r"><span class="header-section-number">9.6</span> Path Analysis in R</a>
  <ul class="collapse">
  <li><a href="#the-path-model-with-lavaan" id="toc-the-path-model-with-lavaan" class="nav-link" data-scroll-target="#the-path-model-with-lavaan"><span class="header-section-number">9.6.1</span> The path model with lavaan</a></li>
  <li><a href="#explantion-of-the-results" id="toc-explantion-of-the-results" class="nav-link" data-scroll-target="#explantion-of-the-results"><span class="header-section-number">9.6.2</span> Explantion of the results</a></li>
  <li><a href="#assessment-of-model-fit" id="toc-assessment-of-model-fit" class="nav-link" data-scroll-target="#assessment-of-model-fit"><span class="header-section-number">9.6.3</span> Assessment of Model Fit</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-path" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mediation and Path Analysis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Get the Code
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can download the complete R script from here:</p>
<p><a href="https://osf.io/download/tby47/" download="psy400_8.R"> <button type="button" class="btn btn-primary"> <i class="bi bi-download"></i> Download R Script </button> </a></p>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Get the Data happiness
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can download the Excel dataset <strong>happiness</strong> from here:</p>
<p><a href="https://osf.io/download/vnqke/" download="happiness.xlsx"> <button type="button" class="btn btn-success"> <i class="bi bi-file-earmark-excel"></i> Download Excel Data </button> </a></p>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Get the Data PlannedBehavior
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can download the Excel dataset <strong>PlannedBehavior</strong> from here:</p>
<p><a href="https://osf.io/download/syaq9/" download="PlannedBehavior.xlsx"> <button type="button" class="btn btn-success"> <i class="bi bi-file-earmark-excel"></i> Download Excel Data </button> </a></p>
</div>
</div>
<p><br></p>
<p>First, we load the following R packages in our R session:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Required packages for this R script</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="mediation-analysis" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="mediation-analysis"><span class="header-section-number">9.1</span> Mediation analysis</h2>
<p>A single mediation analysis is based on the estimation of the four pathways, w, a, b, and c shown in <a href="#fig-path001" class="quarto-xref">Figure&nbsp;<span>9.1</span></a>. In <a href="#fig-path001" class="quarto-xref">Figure&nbsp;<span>9.1</span></a><strong>(A)</strong>, the “w” path represents the total X→Y effect. In <a href="#fig-path001" class="quarto-xref">Figure&nbsp;<span>9.1</span></a><strong>(B)</strong>, the “a” path represents the X→M effect, the “b” path represents the M→Y effect, and the “c” path represents the direct X→Y effect. In traditional mediation analysis, the paths coefficients are estimated using linear regression equations.</p>
<p>Mediation analysis is based on the assumption of temporal precedence of the independent variable X, mediator, and outcome, which means that changes in the X are assumed to precede changes in the mediator, and that changes in the mediator are assumed to precede changes in the outcome.</p>
<p>&nbsp;</p>
<div id="fig-path001" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-path001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/path001.png" class="img-fluid figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-path001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Path diagram of a single mediator model.
</figcaption>
</figure>
</div>
<p>It is important to note that, like any regression-based analysis, mediation analysis cannot establish causal associations unless it is grounded in an experimental design. Drawing causal inferences requires rigorous methodological controls, including random assignment, temporal precedence, and the elimination of alternative explanations.</p>
<p>&nbsp;</p>
<div class="content-box-green">
<p><strong>Direct and indirect effects</strong></p>
<p>Mediation analysis decomposes the total X→Y effect (w) into a direct effect (c) and an indirect effect through a mediator variable, which is the product of a and b (axb).</p>
</div>
<p>&nbsp;</p>
</section>
<section id="example" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="example"><span class="header-section-number">9.2</span> Example</h2>
<p>Assume that previous research has demonstrated that higher grades are associated with increased happiness: X (grades) → Y (happiness) (<a href="#fig-path002" class="quarto-xref">Figure&nbsp;<span>9.2</span></a> A). In our theory, we also hypothesize that good grades enhance self-esteem, which in turn increases happiness: X (grades) → M (self-esteem) → Y (happiness) (<a href="#fig-path001" class="quarto-xref">Figure&nbsp;<span>9.1</span></a> B).</p>
<div id="fig-path002" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-path002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/path002.png" class="img-fluid figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-path002-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: Path diagram of grades, self-esteem, and happiness model.
</figcaption>
</figure>
</div>
<p>&nbsp;</p>
</section>
<section id="import-the-dataset" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="import-the-dataset"><span class="header-section-number">9.3</span> Import the dataset</h2>
<p>If the dataset <em>happiness</em> is saved in the subfolder named “data” of our RStudio project, we can read it with the <code>read_excel()</code> function from <code>readxl</code> package as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dat_happiness <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/happiness.xlsx"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat_happiness</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 3
   grades selfesteem happiness
    &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
 1      6          5         6
 2      7          5         5
 3      7          7         4
 4      8          4         8
 5      4          3         5
 6      4          4         7
 7      9          7         8
 8      5          0         4
 9      8          7         7
10      4          3         4
# ℹ 90 more rows</code></pre>
</div>
</div>
<section id="baron-kenny-method" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="baron-kenny-method"><span class="header-section-number">9.3.1</span> Baron &amp; Kenny method</h3>
<p>The following shows the basic steps for mediation analysis suggested by Baron &amp; Kenny (1986). A mediation analysis is comprised of three sets of regression: (1) X → Y, (2) X → M, and (3) X + M → Y. This 3-step method used to describe a mediation effect. Steps 1 and 2 use basic linear regression while steps 3 use multiple regression.</p>
<ul>
<li><strong>Step 1:</strong> Estimate the association between X on Y (grades on happiness). The <strong>total effect</strong> “w” must be significantly different from 0. If there is no association between X and Y, there is nothing to mediate.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/path4.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption>Total effect of X on Y.</figcaption>
</figure>
</div>
<p><span class="math display">\[Y = intercept \ + \text{w} \cdot X + e\]</span></p>
<p>where <span class="math inline">\(e\)</span> is the residual error of the model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>step_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(happiness <span class="sc">~</span> grades, <span class="at">data =</span> dat_happiness)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = happiness ~ grades, data = dat_happiness)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.0262 -1.2340 -0.3282  1.5583  5.1622 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.8572     0.6932   4.122 7.88e-05 ***
grades        0.3961     0.1112   3.564 0.000567 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.929 on 98 degrees of freedom
Multiple R-squared:  0.1147,    Adjusted R-squared:  0.1057 
F-statistic:  12.7 on 1 and 98 DF,  p-value: 0.0005671</code></pre>
</div>
</div>
<p>&nbsp;</p>
<p><span class="math display">\[happiness = 2.86 \ + 0.40 \cdot grades\]</span> Therefore, the total effect w = 0.40 is statistical significant (p&lt;0.001).</p>
<p>(<strong>NOTE:</strong> Even if we don’t find a significant association between X and Y, we could move forward to the next step if we have a good theoretical background about their association.)</p>
<p>&nbsp;</p>
<ul>
<li><strong>Step 2:</strong> Estimate the association between X on M (grades on self-esteem). Path “a” must be significantly different from 0; The independent variable and the mediator must be associated. If X and M have no association, M is just a third variable that may or may not be associated with Y. A mediation makes sense only if X affects M.</li>
</ul>
<div id="fig-path5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-path5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/path5.png" class="img-fluid figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-path5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: The effect of X on M.
</figcaption>
</figure>
</div>
<p><span class="math display">\[M = intercept \ + \text{a} \cdot X + e\]</span></p>
<p>where <span class="math inline">\(e\)</span> is the residual error of the model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>step_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(selfesteem <span class="sc">~</span> grades, <span class="at">data =</span> dat_happiness)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = selfesteem ~ grades, data = dat_happiness)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3046 -0.8656  0.1344  1.1344  4.6954 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.49952    0.58920   2.545   0.0125 *  
grades       0.56102    0.09448   5.938 4.39e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.639 on 98 degrees of freedom
Multiple R-squared:  0.2646,    Adjusted R-squared:  0.2571 
F-statistic: 35.26 on 1 and 98 DF,  p-value: 4.391e-08</code></pre>
</div>
</div>
<p>&nbsp;</p>
<p><span class="math display">\[selfesteem = 1.50 \ + 0.56 \cdot grades\]</span> Therefore, the effect of X on M (a = 0.56) is statistical significant (p&lt;0.001).</p>
<p>&nbsp;</p>
<ul>
<li><strong>Step 3:</strong> Estimate the effects of both X and M on Y. Path “b” must be significantly different from 0; mediator and outcome must be associated. Additionally, the path “c” should be non-significant and nearly 0. The effect of X on Y will disappear (full mediation) or at least weaken (partial mediation) when M is included in the regression. The effect of X on Y goes through M.</li>
</ul>
<div id="fig-path6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-path6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/path6.png" class="img-fluid figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-path6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.4: The effects of both X and M on Y.
</figcaption>
</figure>
</div>
<p><span class="math display">\[Y = intercept \ + c \cdot X + \text{b} \cdot M + e\]</span></p>
<p>where <span class="math inline">\(e\)</span> is the residual error of the model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>step_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(happiness <span class="sc">~</span> grades <span class="sc">+</span> selfesteem, <span class="at">data =</span> dat_happiness)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = happiness ~ grades + selfesteem, data = dat_happiness)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.7631 -1.2393  0.0308  1.0832  4.0055 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   1.9043     0.6055   3.145   0.0022 ** 
grades        0.0396     0.1096   0.361   0.7187    
selfesteem    0.6355     0.1005   6.321 7.92e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.631 on 97 degrees of freedom
Multiple R-squared:  0.373, Adjusted R-squared:  0.3601 
F-statistic: 28.85 on 2 and 97 DF,  p-value: 1.471e-10</code></pre>
</div>
</div>
<p>&nbsp;</p>
<p><span class="math display">\[happiness = 1.90 \ + 0.04 \cdot grades + 0.64 \cdot selfesteem\]</span></p>
<p>Therefore, the effect of M (self-esteem) on Y (happiness), controlling for X (grades), is statistically significant (b = 0.64, p &lt; 0.001), whereas the effect of X (grades) on Y (happiness), controlling for M (self-esteem), is weakened and not statistically significant (c = 0.04, p = 0.719).</p>
<p>&nbsp;</p>
<p><strong>Total, direct and indirect effects</strong></p>
<ul>
<li><p>The total effect (w = 0.40) is just the coefficient (w) we would find by fitting a simple regression model (e.g., <span class="math inline">\(Y = intercept \ + \text{w} \cdot X\)</span>).</p></li>
<li><p>The indirect effect is the effect of X on Y, through the mediator M. It’s obtained by multiplying <span class="math inline">\(a \times b = 0.56 \times 0.64 = 0.36\)</span>.</p></li>
<li><p>The direct effect (c = 0.04) is the partial effect of of X on Y after controlling for M.</p></li>
</ul>
<div id="fig-path7" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-path7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/path7.png" class="img-fluid figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-path7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.5: Direct and inderect effects.
</figcaption>
</figure>
</div>
<p>In practice, a simple mediation model decompose the total effect of X on Y, in a direct and indirect effect. Therefore:</p>
<p><span class="math display">\[w = c + (a \times b) = 0.04 + (0.56 \times 0.64) = 0.04 + 0.36 = 0.40\]</span></p>
</section>
<section id="mediation-analysis-with-r" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="mediation-analysis-with-r"><span class="header-section-number">9.3.2</span> Mediation Analysis with R</h3>
<p>We specify and estimate our mediation model using the <code>sem()</code> function from the <strong><code>lavaan</code></strong> package in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Define the model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># a = path from grades to self-esteem</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># b = path from self-esteem to happiness</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># c = direct path from grades to happiness</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>mediation_model <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="st">  # Regressions</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="st">  selfesteem ~ a*grades</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="st">  happiness  ~ c*grades + b*selfesteem</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="st">  # Define the effects for the summary output</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="st">  direct   := c</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="st">  indirect := a * b</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="st">  total    := c + (a * b)</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Fit the model </span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>med_model <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="at">model =</span> mediation_model, <span class="at">data =</span> dat_happiness)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. View the results</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_model, <span class="at">standardize =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 1 iteration

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         5

  Number of observations                           100

Model Test User Model:
                                                      
  Test statistic                                 0.000
  Degrees of freedom                                 0

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  selfesteem ~                                                          
    grades     (a)    0.561    0.094    5.998    0.000    0.561    0.514
  happiness ~                                                           
    grades     (c)    0.040    0.108    0.367    0.714    0.040    0.034
    selfesteem (b)    0.635    0.099    6.418    0.000    0.635    0.593

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .selfesteem        2.633    0.372    7.071    0.000    2.633    0.735
   .happiness         2.581    0.365    7.071    0.000    2.581    0.627

Defined Parameters:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
    direct            0.040    0.108    0.367    0.714    0.040    0.034
    indirect          0.357    0.081    4.382    0.000    0.357    0.305
    total             0.396    0.110    3.600    0.000    0.396    0.339</code></pre>
</div>
</div>
<p>The path estimates (regression coefficients):</p>
<ul>
<li><span class="math inline">\(a=0.56\)</span> (p &lt;0.001)</li>
<li><span class="math inline">\(b=0.64\)</span> (&lt;0.001)</li>
<li><span class="math inline">\(c = 0.04\)</span> (p = 0.714).</li>
</ul>
<p>&nbsp;</p>
<p>The mediation estimates:</p>
<ul>
<li>The direct effect (<span class="math inline">\(c = 0.04\)</span>; p = 0.714)</li>
<li>The indirect effect (<span class="math inline">\(a \times b = 0.36\)</span>; p &lt;0.001).</li>
<li>The total effect (<span class="math inline">\(w = c + a \times b = 0.40;\)</span> p&lt;0.001)</li>
</ul>
<p>&nbsp;</p>
<p>We can also represent the mediation estimates in a plot:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ly <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">0</span>,  <span class="dv">1</span>,  </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>,  </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>   </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>), <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(med_model, </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">layout =</span> ly, </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>,           <span class="co"># Use full names</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">shapeMan =</span> <span class="st">"rectangle"</span>,   </span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">18</span>,             </span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan2 =</span> <span class="dv">12</span>,            </span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">residuals =</span> <span class="cn">FALSE</span>,        </span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>,       </span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"white"</span>,          </span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.color =</span> <span class="st">"black"</span>,     </span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.8</span>,     </span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">asize =</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="path_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
</section>
</section>
<section id="path-analysis" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="path-analysis"><span class="header-section-number">9.4</span> Path analysis</h2>
<section id="basic-concepts" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="basic-concepts"><span class="header-section-number">9.4.1</span> Basic concepts</h3>
<p>Path analysis can be used to test more complex theories of <strong>observed variables</strong> (or manifest variables). It is an extension of multiple regression and is used primarily to examine direct and indirect associations among variables.</p>
<p>In this example, we look at the theory of planned behavior (TPB). This theory is a psychological theory that links beliefs to behavior. In its simplified form, the TPB proposes that an individual’s intention to perform a specific behavior influences the individual’s decision to enact that behavior, and attitude toward the behavior, perception of norms pertaining to that behavior, and perception of control over performing that behavior influence the individual’s intention to perform the behavior.</p>
<p>We can specify the Theory of Planned Behavior as a path diagram by drawing the observed variables and the directional associations (paths) between the variables as implied by the theory, where rectangles represent the variables and directional arrows represent the directional relations between variables, which is depicted in the path diagram below:</p>
<div id="fig-path27" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-path27-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/path27.png" class="img-fluid figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-path27-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.6: Model diagram.
</figcaption>
</figure>
</div>
<ul>
<li><p><strong>Exogenous variables:</strong> Independent variables that are influenced by factors outside the model and, in turn, influence endogenous variables. In path diagrams, arrows originate from exogenous variables but do not point to them.</p></li>
<li><p><strong>Endogenous variables:</strong> Dependent variables that are explained by exogenous variables in the model. Arrows point toward them and these represent causal paths. Note that an endogenous variable may also be specified as the predictor of another endogenous variable, as is the case in our example path diagram.</p></li>
<li><p><strong>Path coefficients</strong> are regression coefficients (typically denoted as <span class="math inline">\(\beta_1-\beta_4\)</span>, or sometimes as <span class="math inline">\(p_1-p_4\)</span>) that represent direct effects of one variable on another.</p></li>
<li><p><strong>Variances</strong> are typically represented as curved double-sided arrows, where both arrows point to the same variable. <strong>Covariances</strong> are also represented as double-sided arrows in which the arrows connect two distinct variables.</p></li>
<li><p><strong>(Residual) error terms</strong> (which are sometimes called disturbances) are added to <strong>endogenous variables</strong>.</p></li>
</ul>
<p>The equations of this model are:</p>
<p><span class="math display">\[intention = intercept +  \beta_1 attitude + \beta_2 norms + \beta_3 control + e\]</span></p>
<p>and</p>
<p><span class="math display">\[behavior = intercept + \beta_4 intention + e\]</span></p>
<p>&nbsp;</p>
</section>
<section id="model-identification" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="model-identification"><span class="header-section-number">9.4.2</span> Model Identification</h3>
<p>Model identification refers to determining whether there is sufficient information in the observed data to estimate the model’s parameters (e.g., regression coefficients, variances) uniquely.</p>
<ul>
<li><p>A model is <strong>overidentified</strong> when there are more unique (non-redundant) sources of information than free parameters, which means that the degrees of freedom (df) is greater than zero. This is ideal because it allows for both parameter estimation and model fit testing.</p></li>
<li><p>A <strong>just-identified</strong> model has an equal number of unique sources of information and free parameters; while the model can be estimated, its fit to the data cannot be tested.</p></li>
<li><p>An <strong>underidentified</strong> model has fewer unique sources of information than parameters, meaning it lacks enough information to estimate all free parameters, making it impossible to fit the model reliably.</p></li>
</ul>
<p>The formula for calculating the number of unique (non-redundant) sources of information available for a particular model is as follows:</p>
<p><span class="math display">\[i = \frac{p \cdot (p+1)}{2}\]</span></p>
<p>where <span class="math inline">\(p\)</span> is the number of observed variables to be modeled.</p>
<p>In the path diagram we specified above, there are five observed variables: Attitude, Norms, Control, Intention, and Behavior. Thus, in the following formula, <span class="math inline">\(p\)</span> is equal to 5, and thus the number of unique (non-redundant) sources of information is 15.</p>
<p><span class="math display">\[i = \frac{5 \cdot (5+1)}{2} = \frac{30}{2} = 15\]</span></p>
<p>To count the number of free parameters (<span class="math inline">\(k\)</span>), simply add up the number of the specified direction relations, variances, covariances, and error terms in the path analysis model. In our example:</p>
<p><span class="math display">\[k=12\]</span></p>
<p>To calculate the degrees of freedom (<span class="math inline">\(df\)</span>) for the model, subtract the number of free parameters from the number unique (non-redundant) sources of information, which in this example is equal to 3, as shown below.</p>
<p><span class="math display">\[df = i - k = 15 - 12 = 3\]</span></p>
<p>Thus, the degrees of freedom for the model is 3, which means the model is over-identified.</p>
<p>&nbsp;</p>
</section>
<section id="model-fit-in-path-analysis" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="model-fit-in-path-analysis"><span class="header-section-number">9.4.3</span> Model Fit in path analysis</h3>
<p>There are many measures of fit in path analysis:</p>
<div id="fig-cfa501" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cfa501-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/cfa501.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cfa501-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.7: Measures of fit in Confirmatory Factor Analysis.
</figcaption>
</figure>
</div>
<ul>
<li><p><strong>Chi-square test</strong>. The chi-square test can be used to assess whether the model fits the data adequately. A non-significant chi-square value (e.g., p ≥ 0.05) indicates that the model fits the data reasonably well. However, the test is highly sensitive to sample size—tending to yield non-significant results in small samples even when fit is poor, and significant results in large samples even when the model fits well.</p></li>
<li><p><strong>The Comparative Fit Index (CFI):</strong> The CFI is an incremental fit index, meaning it evaluates how much the hypothesized model improves upon a baseline (or null) model that assumes no associations among variables. CFI values range from 0 to 1, with higher values indicating better fit. (Rule of thumb: CFI values above 0.90 are generally considered indicative of acceptable model fit, while values above 0.95 suggest a good model fit).</p></li>
<li><p><strong>Tucker-Lewis Index (TLI):</strong> The TLI penalizes model complexity more heavily than the CFI. TLI values can sometimes exceed 1.0, making the index somewhat unstable. Given the close association between TLI and CFI, it is generally recommended to report only one of the two.</p></li>
<li><p><strong>RMSEA (Root Mean Square Error of Approximation):</strong> The RMSEA is an absolute fit index interpreted as a badness-of-fit measure, with 0.00 indicating a perfect fit. It tends to favor models with more degrees of freedom and larger sample sizes. A unique feature of RMSEA is that it is accompanied by a 90% confidence interval. Although there is ongoing debate about acceptable RMSEA values, a common consensus is that <span class="math inline">\(RMSEA \geq 0.10\)</span> indicates poor fit, while <span class="math inline">\(RMSEA \leq 0.05\)</span> suggests a good fit. When interpreting the RMSEA, it’s important to examine the upper bound of the confidence interval to ensure it does not approach problematic levels.</p></li>
<li><p><strong>SRMR (Standardized Root Mean Square Residual):</strong> The SRMR is another absolute fit index and, like RMSEA, is a badness-of-fit statistic—values closer to 0.00 indicate better fit. The SRMR is a standardized version of the Root Mean Square Residual (RMR), which measures the mean absolute covariance residual. Standardization facilitates interpretation across different models. Poor model fit is typically flagged when <span class="math inline">\(SRMR \geq 0.10\)</span>.</p></li>
</ul>
<p>According to Hu and Bentler (1999), an acceptable fit is achieved when <span class="math inline">\(CFI \geq 0.95\)</span> and <span class="math inline">\(SRMR \leq 0.08\)</span>—a guideline known as the combination rule. This recommendation, however, remains a topic of debate.</p>
<p>The conventional cutoffs for the aforementioned model fit indices – like any rule of thumb – should be applied with caution. Additionally, these indices do not always align with one another, which is why researchers often examine multiple fit indices to make an informed judgment about whether a model adequately fits the data.</p>
<p>&nbsp;</p>
</section>
</section>
<section id="import-the-dataset-1" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="import-the-dataset-1"><span class="header-section-number">9.5</span> Import the dataset</h2>
<p>If the dataset <em>PlannedBehavior</em> is saved in the subfolder named “data” of our RStudio project, we can read it with the <code>read_excel()</code> function from <code>readxl</code> package as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>dat_behavior <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/PlannedBehavior.xlsx"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>dat_behavior</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 199 × 5
   attitude norms control intention behavior
      &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1     2.31  2.31    2.03      2.5      2.62
 2     4.66  4.01    3.63      3.99     3.64
 3     3.85  3.56    4.2       4.35     3.83
 4     4.24  2.25    2.84      1.51     2.25
 5     2.91  3.31    2.4       1.45     2   
 6     2.99  2.51    2.95      2.59     2.2 
 7     3.96  4.65    3.77      4.08     4.41
 8     3.01  2.98    1.9       2.58     4.15
 9     4.77  3.09    3.83      4.87     4.35
10     3.67  3.63    5         3.09     3.95
# ℹ 189 more rows</code></pre>
</div>
</div>
<p>There are 5 variables and 199 cases in the data frame.</p>
</section>
<section id="path-analysis-in-r" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="path-analysis-in-r"><span class="header-section-number">9.6</span> Path Analysis in R</h2>
<section id="the-path-model-with-lavaan" class="level3" data-number="9.6.1">
<h3 data-number="9.6.1" class="anchored" data-anchor-id="the-path-model-with-lavaan"><span class="header-section-number">9.6.1</span> The path model with lavaan</h3>
<p>We specify and estimate our path model using the <code>sem()</code> function from the <strong><code>lavaan</code></strong> package in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the path model for Theory of Planned Behavior</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>tpb_model <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="st">  # Predicting Intention</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="st">  intention ~ b1*attitude + b2*norms + b3*control</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="st">  # Predicting Behavior</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="st">  behavior ~ b4*intention</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="st">  # Intercepts (Explicitly defined)</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="st">  intention ~ 1</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="st">  behavior ~ 1</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="st">  # Indirect effects</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="st">  indirect_att := b1 * b4</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="st">  indirect_norm := b2 * b4</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="st">  indirect_ctrl := b3 * b4</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>tpb_fit <span class="ot">&lt;-</span> <span class="fu">sem</span>(tpb_model, <span class="at">data =</span> dat_behavior)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tpb_fit, </span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, </span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">standardized =</span> <span class="cn">TRUE</span>, </span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">rsquare =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 2 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         8

  Number of observations                           199

Model Test User Model:
                                                      
  Test statistic                                 2.023
  Degrees of freedom                                 3
  P-value (Chi-square)                           0.568

Model Test Baseline Model:

  Test statistic                               137.622
  Degrees of freedom                                 7
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    1.000
  Tucker-Lewis Index (TLI)                       1.017

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)               -465.934
  Loglikelihood unrestricted model (H1)       -464.922
                                                      
  Akaike (AIC)                                 947.868
  Bayesian (BIC)                               974.214
  Sample-size adjusted Bayesian (SABIC)        948.870

Root Mean Square Error of Approximation:

  RMSEA                                          0.000
  90 Percent confidence interval - lower         0.000
  90 Percent confidence interval - upper         0.103
  P-value H_0: RMSEA &lt;= 0.050                    0.735
  P-value H_0: RMSEA &gt;= 0.080                    0.120

Standardized Root Mean Square Residual:

  SRMR                                           0.017

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  intention ~                                                           
    attitude  (b1)    0.352    0.058    6.068    0.000    0.352    0.370
    norms     (b2)    0.153    0.059    2.577    0.010    0.153    0.152
    control   (b3)    0.275    0.058    4.740    0.000    0.275    0.291
  behavior ~                                                            
    intention (b4)    0.453    0.065    7.014    0.000    0.453    0.445

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .intention         0.586    0.237    2.470    0.014    0.586    0.639
   .behavior          1.743    0.203    8.595    0.000    1.743    1.867

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .intention         0.530    0.053    9.975    0.000    0.530    0.631
   .behavior          0.699    0.070    9.975    0.000    0.699    0.802

R-Square:
                   Estimate
    intention         0.369
    behavior          0.198

Defined Parameters:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
    indirect_att      0.160    0.035    4.589    0.000    0.160    0.165
    indirect_norm     0.069    0.029    2.419    0.016    0.069    0.067
    indirect_ctrl     0.125    0.032    3.927    0.000    0.125    0.129</code></pre>
</div>
</div>
<p>&nbsp;</p>
</section>
<section id="explantion-of-the-results" class="level3" data-number="9.6.2">
<h3 data-number="9.6.2" class="anchored" data-anchor-id="explantion-of-the-results"><span class="header-section-number">9.6.2</span> Explantion of the results</h3>
<p>Let’s examine the most interesting results separately for each group of estimates and measures.</p>
<p><strong>Intercepts of the model equations</strong></p>
<p>The intercepts of the equations of the model are following:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        lhs   est    se     z pvalue ci.lower ci.upper std.all
5 intention 0.586 0.237 2.470  0.014    0.121    1.051   0.639
6  behavior 1.743 0.203 8.595  0.000    1.345    2.140   1.867</code></pre>
</div>
</div>
<p>&nbsp;</p>
<p><strong>Regression (Path) Coefficients</strong></p>
<p>The direct effects (path coefficients) are obtained from regression analysis. The following table summarizes hypotheses testing results of the study.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        lhs       rhs label   est    se     z pvalue ci.lower ci.upper std.all
1 intention  attitude    b1 0.352 0.058 6.068   0.00    0.239    0.466   0.370
2 intention     norms    b2 0.153 0.059 2.577   0.01    0.036    0.269   0.152
3 intention   control    b3 0.275 0.058 4.740   0.00    0.161    0.389   0.291
4  behavior intention    b4 0.453 0.065 7.014   0.00    0.327    0.580   0.445</code></pre>
</div>
</div>
<p>The path coefficient (i.e., regression coefficient b) between attitude and intention is statistically significant and positive (<span class="math inline">\(b_1 = 0.352\)</span>, p &lt; 0.001). The path coefficient between norms and intention is statistically significant and positive (<span class="math inline">\(b_2 = 0.153\)</span>, p = 0.010). The path coefficient between control and intention is statistically significant and positive (<span class="math inline">\(b_3 = 0.275\)</span>, p &lt; 0.001). Of the three predictors of intention, attitude exhibited the strongest relative effect (i.e., the statndardized estimate is <span class="math inline">\(std.all = 0.370\)</span>). Finally, the path coefficient between intention and behavior is statistically significant and positive (<span class="math inline">\(b_4 = 0.453\)</span>, p &lt; 0.001).</p>
<p>&nbsp;</p>
<p>According to results of the above tables, the equations can be expressed as follows:</p>
<p><span class="math display">\[intention = 0.586 + 0.352 \cdot attitude + 0.153 \cdot norms + 0.275 \cdot control\]</span></p>
<p>and</p>
<p><span class="math display">\[behavior = 1.743 + 0.453 \cdot intention\]</span></p>
<p>&nbsp;</p>
<p><strong>R-Squared values</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>intention  behavior 
    0.369     0.198 </code></pre>
</div>
</div>
<p>We see the R-Squared value for the outcome variable intention, which is equal to 0.369; that is, collectively, attitude, norms, and control explain 36.9% of the variance in intention. Additionally, intention explains 19.8% of the variance in behavior.</p>
<p>&nbsp;</p>
<p><strong>Indirect Effects</strong></p>
<p>Moreover, the indirect effects are reported in the following table:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             lhs   rhs   est    se     z pvalue ci.lower ci.upper std.all
18  indirect_att b1*b4 0.160 0.035 4.589  0.000    0.092    0.228   0.165
19 indirect_norm b2*b4 0.069 0.029 2.419  0.016    0.013    0.125   0.067
20 indirect_ctrl b3*b4 0.125 0.032 3.927  0.000    0.062    0.187   0.129</code></pre>
</div>
</div>
<p>For example, the estimate for the indirect effect of the path attitude=&gt;intention=&gt;behavior is calculated as 0.35*0.45 = 0.16.</p>
<p>&nbsp;</p>
<p><strong>Variances and Covariances</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         lhs       rhs   est    se     z pvalue ci.lower ci.upper std.all
7  intention intention 0.530 0.053 9.975      0    0.426    0.634   0.631
8   behavior  behavior 0.699 0.070 9.975      0    0.561    0.836   0.802
9   attitude  attitude 0.928 0.000    NA     NA    0.928    0.928   1.000
10  attitude     norms 0.200 0.000    NA     NA    0.200    0.200   0.227
11  attitude   control 0.334 0.000    NA     NA    0.334    0.334   0.357
12     norms     norms 0.830 0.000    NA     NA    0.830    0.830   1.000
13     norms   control 0.220 0.000    NA     NA    0.220    0.220   0.249
14   control   control 0.939 0.000    NA     NA    0.939    0.939   1.000</code></pre>
</div>
</div>
<p>Using path analysis, we can also explicitly model the variance of the exogenous variables (e.g., attitude-attitude variance = 0.93), the covariances (correlations) between the exogenous variables (e.g., norms-attitude covariance= 0.20), and the residual errors of the endogenous variables in the model (e.g., intention res. error = 0.53).</p>
<p>&nbsp;</p>
<p>We can also present the model with a path diagram. All options regard aesthetics of the diagram are shown below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Define the grid layout manually</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Rows represent vertical position, Columns represent horizontal flow</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>ly <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>ly[<span class="dv">1</span>, <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">"attitude"</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>ly[<span class="dv">2</span>, <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">"norms"</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>ly[<span class="dv">3</span>, <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">"control"</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>ly[<span class="dv">2</span>, <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">"intention"</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>ly[<span class="dv">2</span>, <span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="st">"behavior"</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Plot without the 'groups' argument to avoid the subscript error</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(tpb_fit, </span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">whatLabels =</span> <span class="st">"est"</span>,    <span class="co"># Show standardized weights</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">layout =</span> ly, </span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">style =</span> <span class="st">"ram"</span>,      <span class="co"># Professional SEM style</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>,        <span class="co"># Don't abbreviate variable names</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>,    <span class="co"># Don't plot the constant/intercept nodes</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">residuals =</span> <span class="cn">TRUE</span>,      <span class="co"># Show the error terms</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan =</span> <span class="dv">12</span>,          <span class="co"># Size of the boxes</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">sizeMan2 =</span> <span class="dv">8</span>, </span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>),</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.2</span>,  <span class="co"># Size of the path numbers</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">fade =</span> <span class="cn">FALSE</span>,          <span class="co"># Keep all lines solid black for print</span></span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"white"</span>,       <span class="co"># Standard textbook white boxes</span></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>         <span class="at">edge.color =</span> <span class="st">"black"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="path_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="assessment-of-model-fit" class="level3" data-number="9.6.3">
<h3 data-number="9.6.3" class="anchored" data-anchor-id="assessment-of-model-fit"><span class="header-section-number">9.6.3</span> Assessment of Model Fit</h3>
<p>The path model for the Theory of Planned Behavior demonstrated an excellent fit to the data. The chi-square test was non-significant, <span class="math inline">\(\chi^2(3) = 2.023, p = 0.568\)</span>, suggesting no significant discrepancy between the hypothesized model and the observed data. Complementary fit indices further supported this conclusion, with a Comparative Fit Index (CFI) of <span class="math inline">\(1.000\)</span> and a Tucker-Lewis Index (TLI) of <span class="math inline">\(1.017\)</span>, both exceeding the traditional <span class="math inline">\(0.95\)</span> threshold for superior fit. The Root Mean Square Error of Approximation (RMSEA) was <span class="math inline">\(0.000\)</span> (<span class="math inline">\(90\%\)</span> CI <span class="math inline">\([0.000, 0.103]\)</span>), and the Standardized Root Mean Square Residual (SRMR) was <span class="math inline">\(0.017\)</span>, well below the recommended <span class="math inline">\(0.05\)</span> and <span class="math inline">\(0.08\)</span> cut-offs, respectively. Overall, these measures indicate that the model provides a highly robust representation of the relationships between attitude, social norms, perceived control, intention, and behavior</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./multiplelinear.html" class="pagination-link" aria-label="Multiple Linear regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Multiple Linear regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./efa.html" class="pagination-link" aria-label="Exploratory Factor Analysis">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Exploratory Factor Analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2025-26, Konstantinos I. Bougioukas. License: <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivs 4.0</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a><sup>®</sup></p>
</div>
  </div>
</footer>




</body></html>